// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedbackUploadResponse = { threadId: string, 
/**
 * Where the report was written. Nothing is sent anywhere: the file is for
 * the reporter to read, redact and attach to an issue if they choose to.
 */
reportPath: string, };
