// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSearchAction } from "../WebSearchAction";
import type { JsonValue } from "../serde_json/JsonValue";
import type { CollabAgentState } from "./CollabAgentState";
import type { CollabAgentTool } from "./CollabAgentTool";
import type { CollabAgentToolCallStatus } from "./CollabAgentToolCallStatus";
import type { CommandAction } from "./CommandAction";
import type { CommandExecutionStatus } from "./CommandExecutionStatus";
import type { FileUpdateChange } from "./FileUpdateChange";
import type { McpToolCallError } from "./McpToolCallError";
import type { McpToolCallResult } from "./McpToolCallResult";
import type { McpToolCallStatus } from "./McpToolCallStatus";
import type { PatchApplyStatus } from "./PatchApplyStatus";
import type { UserInput } from "./UserInput";

export type ThreadItem = { "type": "userMessage", id: string, content: Array<UserInput>, } | { "type": "agentMessage", id: string, text: string, } | { "type": "plan", id: string, text: string, } | { "type": "reasoning", id: string, summary: Array<string>, content: Array<string>, 
/**
 * How long the model spent on it, when that can be worked out.
 * Nothing records it directly; for a reopened conversation it is the
 * gap between this record and the one before it.
 */
durationMs: number | null, } | { "type": "commandExecution", id: string, 
/**
 * The command to be executed.
 */
command: string, 
/**
 * The command's working directory.
 */
cwd: string, 
/**
 * Identifier for the underlying PTY process (when available).
 */
processId: string | null, status: CommandExecutionStatus, 
/**
 * A best-effort parsing of the command to understand the action(s) it will perform.
 * This returns a list of CommandAction objects because a single shell command may
 * be composed of many commands piped together.
 */
commandActions: Array<CommandAction>, 
/**
 * What the command is for, in the model's own words, when it wrote
 * any. Often absent, so a front end showing it must be able to fall
 * back to `command_actions` or to the command itself.
 */
description?: string, 
/**
 * The command's output, aggregated from stdout and stderr.
 */
aggregatedOutput: string | null, 
/**
 * The command's exit code.
 */
exitCode: number | null, 
/**
 * The duration of the command execution in milliseconds.
 */
durationMs: number | null, } | { "type": "fileChange", id: string, changes: Array<FileUpdateChange>, status: PatchApplyStatus, } | { "type": "mcpToolCall", id: string, server: string, tool: string, status: McpToolCallStatus, arguments: JsonValue, result: McpToolCallResult | null, error: McpToolCallError | null, 
/**
 * The duration of the MCP tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "collabAgentToolCall", 
/**
 * Unique identifier for this collab tool call.
 */
id: string, 
/**
 * Name of the collab tool that was invoked.
 */
tool: CollabAgentTool, 
/**
 * Current status of the collab tool call.
 */
status: CollabAgentToolCallStatus, 
/**
 * Thread ID of the agent issuing the collab request.
 */
senderThreadId: string, 
/**
 * Thread ID of the receiving agent, when applicable. In case of spawn operation,
 * this corresponds to the newly spawned agent.
 */
receiverThreadIds: Array<string>, 
/**
 * Prompt text sent as part of the collab tool call, when available.
 */
prompt: string | null, 
/**
 * Last known status of the target agents, when available.
 */
agentsStates: { [key in string]?: CollabAgentState }, } | { "type": "webSearch", id: string, query: string, action: WebSearchAction | null, } | { "type": "imageView", id: string, path: string, } | { "type": "enteredReviewMode", id: string, review: string, } | { "type": "exitedReviewMode", id: string, review: string, } | { "type": "contextCompaction", id: string, };
