// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";
import type { TurnError } from "./TurnError";
import type { TurnStatus } from "./TurnStatus";

export type Turn = { id: string, 
/**
 * Only populated on a `thread/resume` or `thread/fork` response.
 * For all other responses and notifications returning a Turn,
 * the items field will be an empty list.
 */
items: Array<ThreadItem>, status: TurnStatus, 
/**
 * Only populated when the Turn's status is failed.
 */
error: TurnError | null, 
/**
 * How long the whole turn took, in milliseconds.
 *
 * Only this. A live client can also time the wait before the model says
 * anything, but a rollout cannot: a thought is recorded when it finishes,
 * so the gap from the request to that record is the wait and the thinking
 * together, with nothing to tell them apart. Reporting it as a wait would
 * show the same span twice, once as a wait and again as the thought.
 */
totalMs: number | null, };
