// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenCLIErrorInfo } from "./OpenCLIErrorInfo";

export type TurnError = { message: string, opencliErrorInfo: OpenCLIErrorInfo | null, additionalDetails: string | null, };
