// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecCommandSource } from "./ExecCommandSource";
import type { ParsedCommand } from "./ParsedCommand";

export type ExecCommandBeginEvent = { 
/**
 * Identifier so this can be paired with the ExecCommandEnd event.
 */
call_id: string, 
/**
 * Identifier for the underlying PTY process (when available).
 */
process_id?: string, 
/**
 * Turn ID that this command belongs to.
 */
turn_id: string, 
/**
 * The command to be executed.
 */
command: Array<string>, 
/**
 * The command's working directory if not the default cwd for the agent.
 */
cwd: string, parsed_cmd: Array<ParsedCommand>, 
/**
 * What the command is for, in the model's own words, when it wrote any.
 *
 * Often absent: a smaller model routinely skips a field it is not
 * required to fill, so a reader of this must be able to do without it.
 */
description?: string, 
/**
 * Where the command originated. Defaults to Agent for backward compatibility.
 */
source: ExecCommandSource, 
/**
 * Raw input sent to a unified exec session (if this is an interaction event).
 */
interaction_input?: string, };
