// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenCLIErrorInfo } from "./OpenCLIErrorInfo";

export type StreamErrorEvent = { message: string, opencli_error_info: OpenCLIErrorInfo | null, 
/**
 * Optional details about the underlying stream failure (often the same
 * human-readable message that is surfaced as the terminal error if retries
 * are exhausted).
 */
additional_details: string | null, };
